openapi: 3.0.3
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3001/api/v1
tags:
  - name: User Bank Account
    description: Operations about user
paths:
  /user/bankAccount:
    get:
      tags:
        - User Bank Account
      summary: All Bank Accounts Summary
      description: API for read all accounts of the user
      operationId: createUser
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
      security:
        - api_key: []
  /user/{accountId}:
    get:
      tags:
        - User Bank Account
      summary: Account
      description: API for read transactions of the account
      parameters:
        - name: accountId
          in: path
          description: ID of the account
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountIdResponse' 
        default:
          description: successful operation
      security:
        - api_key: []
        - bankstore_auth:
            - read:bank
  /user/bankAccount/{transactionId}:
    post:
      tags:
        - User Bank Account
      summary: User Transactions API
      description: API for read the transaction selected
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction
          schema:
            $ref: '#/components/schemas/Transaction'
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse' 
        default:
          description: successful operation
      security:
        - api_key: []
        - bankstore_auth:
            - read:bank
            - write:bank
    put:
      tags:
        - User Bank Account
      summary: User Transactions API
      description: API for read the transaction selected
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction
          schema:
            $ref: '#/components/schemas/Transaction'
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse' 
        default:
          description: successful operation
      security:
        - api_key: []
        - bankstore_auth:
            - read:bank
            - write:bank
    
components:
  schemas:
    BankAccount:
      type: object
      properties:
        id:
          type: string
          description: Account ID
        accountName:
          type: string
          description: Account Name
        amount:
          type: number
          description: Account amount
        balance:
          type: string
          description: Balance
    AccountId:
      type: object
      properties:
        id:
          type: string
          description: Account ID
    AccountIdResponse:
      type: object
      properties:
        id:
          type: string
          description: Account ID
        accountName:
          type: string
          description: Account Name
        month:
          type: string
          format: date-time
          description: current month
        transactionId:
          type: integer
          description: transaction of the account 
        amount:
          type: number
          description: Account amount
        balance:
          type: string
          description: Balance
    Transaction:
      type: object
      properties:
        id:
          type: string
          description: Transaction ID
    TransactionResponse:
      type: object
      properties:
        annotation:
          type: string
          description: Note for the Transaction
        category:
          type: string
          description: Category ofs the Transaction
    
  securitySchemes:
    bankstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost:3001/api/v1/oauth/authorize
          scopes:
            write:bank: modify notes in your account
            read:bank: read your account
    api_key:
      type: apiKey
      name: api_key
      in: header
